version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  web:
    build: .
    environment:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres@db
    ports:
    - '3000:3000'
    depends_on:
      - db
