default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: not_analytics_development

test:
  <<: *default
  database: not_analytics_test

production:
  <<: *default
  database: not_analytics_production
  username: not_analytics
  password: <%= ENV['NOT_ANALYTICS_DATABASE_PASSWORD'] %>
