name: On push

on: push

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: docker compose -f docker-compose.test.yml build
      - run: docker compose -f docker-compose.test.yml run web rails test

  docker:
    name: 'Test Docker image'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: docker compose -f docker-compose.production.yml up -d --build --wait
      - run: curl -Is http://localhost:3000/healthcheck

  deploy:
    name: 'Deploy'
    needs: [test, docker]
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest

    concurrency:
      group: deploy
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v6
      - uses: 12joan/build-and-push-image@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
